# -*- coding: utf-8 -*-
"""lda-himank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12zx-jsZowxlpoN5yMB7CbRrZWVJVBfMu
"""

import nltk
nltk.download('stopwords')
nltk.download('wordnet')
import re
import numpy as np
import pandas as pd
from pprint import pprint
import os
from pathlib import Path
import json
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import wordnet as wn
import csv
import random
import gensim
import gensim.corpora as corpora
from gensim.utils import simple_preprocess
from gensim.models import CoherenceModel
from gensim.test.utils import datapath
import spacy
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
import json

with open('doc_term_matrix.json', 'r') as outfile:
    doc_term_matrix = json.load(outfile)

dictionary = corpora.Dictionary.load_from_text('dict_10k')

Lda = gensim.models.wrappers.LdaMallet
# ldamodel = Lda(doc_term_matrix, num_topics=100, id2word = dictionary, passes=50)
ldamodel = Lda('Mallet/bin/mallet', corpus=doc_term_matrix, num_topics=100, id2word = dictionary, optimize_interval=10, iterations=5000)
